// <auto-generated />
using BLRI.Mvc.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace BLRI.Mvc.Migrations
{
    [DbContext(typeof(MyDatabaseContext))]
    [Migration("20180809064624_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("BLRI.Mvc.Models.RegistrationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CardholderName")
                        .IsRequired();

                    b.Property<string>("ConfirmPassword")
                        .IsRequired();

                    b.Property<string>("CreditCardNumber")
                        .IsRequired();

                    b.Property<DateTime>("DateOfRegistration");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<bool>("MembershipAutoRenew");

                    b.Property<bool>("Offers");

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("SecurityCode")
                        .IsRequired();

                    b.Property<int>("SubscriptionType");

                    b.Property<bool>("TermsOfService");

                    b.Property<string>("Username")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Registration");
                });

            modelBuilder.Entity("BLRI.Mvc.Models.SubscriptionTypeLookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int?>("RegistrationModelId");

                    b.Property<int>("Value");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationModelId");

                    b.ToTable("SubscriptionTypeLookup");
                });

            modelBuilder.Entity("BLRI.Mvc.Models.SubscriptionTypeLookup", b =>
                {
                    b.HasOne("BLRI.Mvc.Models.RegistrationModel")
                        .WithMany("SubscriptionLookups")
                        .HasForeignKey("RegistrationModelId");
                });
#pragma warning restore 612, 618
        }
    }
}
